export const departmentCodes = {
    "Actuarial Science": "ACTURSCI",
    "American Sign Language": "ASL",
    "American Studies": "AMERICAN",
    "Analytics and Decision Science": "ADS",
    "Anatomy and Cell Biology": "ANATCELL",
    "Anthropology": "ANTHRO",
    "Applied Mathematics": "APPLMATH",
    "Arabic": "ARABIC",
    "Art History": "AH",
    "Artificial Intelligence SysEng": "AISE",
    "Arts and Humanities": "ARTHUM",
    "Astronomy": "ASTRONOM",
    "Biblical Studies": "BIBLSTUD",
    "Biochemistry": "BIOCHEM",
    "Biology": "BIOLOGY",
    "Biomedical Engineering": "BME",
    "Biostatistics": "BIOSTATS",
    "Business Administration": "BUSINESS",
    "Calculus": "CALCULUS",
    "Centre for Global Studies": "CGS",
    "Chem & Biochem Engineering": "CBE",
    "Chemical Biology": "CHEMBIO",
    "Chemistry": "CHEM",
    "Childhood and Youth Studies": "CYS",
    "Chinese": "CHINESE",
    "Church History": "CHURCH",
    "Church Law": "CHURLAW",
    "Church Music": "CHURMUSI",
    "Civil & Envrnmntl Engineering": "CEE",
    "Classical Studies": "CLASSICS",
    "Combined Program Enrollment": "CMBPROG",
    "Communication Sci & Disorders": "COMMSCI",
    "Comparative Lit & Culture": "COMPLIT",
    "Computer Science": "COMPSCI",
    "Creative Arts": "CA",
    "Dance": "DANCE",
    "Data Science": "DATASCI",
    "Digital Communication": "DIGICOMM",
    "Digital Humanities": "DIGIHUM",
    "Disability Studies": "DISABST",
    "Earth Sciences": "EARTHSCI",
    "Economics": "ECONOMIC",
    "Education": "EDUC",
    "Elect & Computer Engineering": "ECE",
    "Engineering Leadership & Innov": "ELI",
    "Engineering Science": "ENGSCI",
    "English": "ENGLISH",
    "Environmental Science": "ENVIRSCI",
    "Epidemiology": "EPID",
    "Epidemiology & Biostatistics": "EPIDEMIO",
    "FIMS": "FIMS",
    "Family Studies & Human Develop": "FAMLYSTU",
    "Field Education": "FLDEDUC",
    "Film Studies": "FILM",
    "Financial Modelling": "FINMOD",
    "Foods and Nutrition": "FOODNUTR",
    "French": "FRENCH",
    "Gender, Sexuality, & Womens St": "GSWS",
    "Geography": "GEOGRAPH",
    "German": "GERMAN",
    "Global Great Books": "GGB",
    "Governance,Leadership & Ethics": "GLE",
    "Greek": "GREEK",
    "Green Process Engineering": "GPE",
    "Health Sciences": "HEALTSCI",
    "Hebrew": "HEBREW",
    "Historical Theology": "HISTTHEO",
    "History": "HISTORY",
    "History of Science": "HISTSCI",
    "Homiletics": "HOMILET",
    "Human Ecology": "HUMANECO",
    "Human Rights Studies": "HUMANRS",
    "Indigenous Studies": "INDIGSTU",
    "Integrated Engineering": "IE",
    "Integrated Science": "INTEGSCI",
    "Intercultural Communications": "ICC",
    "Interdisciplinary Studies": "INTERDIS",
    "International Relations": "INTREL",
    "Italian": "ITALIAN",
    "Japanese": "JAPANESE",
    "Jewish Studies": "JEWISH",
    "Kinesiology": "KINESIOL",
    "Latin": "LATIN",
    "Law": "LAW",
    "Leadership Studies": "LS",
    "Linguistics": "LINGUIST",
    "Liturgical Studies": "LITURST",
    "Liturgics": "LITURGIC",
    "Management & Organizational St": "MOS",
    "Mathematics": "MATH",
    "Mech & Materials Engineering": "MME",
    "Mechatronic Systems Engineerin": "MSE",
    "Media, Information &Technocult": "MIT",
    "Medical Bioinformatics": "MBI",
    "Medical Biophysics": "MEDBIO",
    "Medical Sciences": "MEDSCIEN",
    "Medieval Studies": "MEDIEVAL",
    "Microbiology & Immunology": "MICROIMM",
    "Moral Theology": "MORALTHE",
    "Museum and Curatorial Studies": "MCS",
    "Music": "MUSIC",
    "Neuroscience": "NEURO",
    "Numerical & Mathematical Methd": "NMM",
    "Nursing": "NURSING",
    "One Health": "ONEHEALT",
    "Pastoral Theology": "PASTTHEO",
    "Pathology": "PATHOL",
    "Pharmacology": "PHARM",
    "Philosophical Studies": "PHILST",
    "Philosophy": "PHILOSOP",
    "Physics": "PHYSICS",
    "Physiology": "PHYSIOL",
    "Physiology and Pharmacology": "PHYSPHRM",
    "Political Science": "POLISCI",
    "Politics, Philosophy, Economic": "PPE",
    "Psychology": "PSYCHOL",
    "Rehabilitation Sciences": "REHABSCI",
    "Religious Education": "RELEDUC",
    "Religious Studies": "RELSTUD",
    "Sacramental Theology": "SACRTHEO",
    "Scholars Electives": "SCHOLARS",
    "Science": "SCIENCE",
    "Social Justice & Peace Studies": "SOCLJUST",
    "Social Science": "SOCSCI",
    "Social Work": "SOCWORK",
    "Sociology": "SOCIOLOG",
    "Software Engineering": "SE",
    "Spanish": "SPANISH",
    "Speech": "SPEECH",
    "Spiritual Theology": "SPIRTHEO",
    "Statistical Sciences": "STATS",
    "Studio Art": "SA",
    "Supervised Pastoral Education": "SUPPAST",
    "Systematic Theology": "SYSTHEO",
    "Thanatology": "THANAT",
    "The New Liberal Arts": "TNLA",
    "Theatre Studies": "THEATRE",
    "Theological Ethics": "THEOETH",
    "Theological Studies": "THEOLST",
    "Thesis": "THESIS",
    "Transitional Justice": "TJ",
    "Undergraduate Studies": "UGRD",
    "Western English Language Cen": "WELC",
    "Writing": "WRITING"
  }